version: '3'
services:
  blog_app:
    image: blog_app:1.0
    container_name: blog_app
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
      - .env 