services:
  blog_app:
    build:
      context: .
    container_name: blog_app
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
      - .env
