apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
spec:
  selector:
    app: apiserver
  ports:
    - protocol: TCP
      port: 5000         # 외부에 노출할 포트
      targetPort: 5000   # Pod 내부의 Flask 포트
  type: LoadBalancer
